apiVersion: v2
name: calibre-web
description: A Helm chart for calibre-web
type: application
version: 0.2.0
# renovate datasource=docker depName=lscr.io/linuxserver/calibre-web
appVersion: 'version-0.6.21'
