apiVersion: v2
name: lazylibrarian
description: A Helm chart for LazyLibrarian
type: application
version: 0.2.0
# renovate datasource=docker depName=lscr.io/linuxserver/lazylibrarian
appVersion: 'latest'
